version: "3.9"
services:
    db:
        ports: 
            - 5432:5432
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: "${PASSWORD}"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    mq:
        ports: 
            - 5672:5672
            - 15672:15672
        image: "rabbitmq"

volumes:
    postgres-data:
    